# Generated by Django 5.1.1 on 2026-08-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
