# Generated by Django 5.1.1 on 2026-08-28 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('open_tickets', models.PositiveIntegerField(default=0)),
                ('in_progress_tickets', models.PositiveIntegerField(default=0)),
                ('waiting_customer_tickets', models.PositiveIntegerField(default=0)),
                ('resolved_tickets', models.PositiveIntegerField(default=0)),
                ('closed_tickets', models.PositiveIntegerField(default=0)),
                ('urgent_tickets', models.PositiveIntegerField(default=0)),
                ('high_priority_tickets', models.PositiveIntegerField(default=0)),
                ('average_resolution_minutes', models.FloatField(blank=True, null=True)),
                ('tickets_by_category', models.JSONField(blank=True, default=dict)),
                ('tickets_by_priority', models.JSONField(blank=True, default=dict)),
                ('tickets_by_status', models.JSONField(blank=True, default=dict)),
                ('tickets_by_team', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'date'), name='unique_analytics_snapshot_per_organization_date')],
            },
        ),
    ]
